services:
  litellm:
    image: ${IMAGE:-docker.litellm.ai/berriai/litellm:main-stable}
    container_name: ${NAME:-litellm}
    restart: ${RESTART:-unless-stopped}

    # build:
    #   context: ../../../DATA/ai-stack/litellm
    #   dockerfile: Dockerfile
    #   args:
    #     UID: ${PUID:-1000}
    #     GID: ${PGID:-1000}
    #     target: runtime

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}

      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-sk-admin}
      - UI_USERNAME=${UI_USERNAME:-admin}
      - UI_PASSWORD=${UI_PASSWORD:-admin}
      # - DOCS_URL=${DOCS_URL:-/docs}
      # - ROOT_REDIRECT_URL=${ROOT_REDIRECT_URL:-/ui}
      # - DISABLE_ADMIN_UI=${DISABLE_ADMIN_UI:-True}

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      # - litellm_data:/litellm
      - ../../../DATA/ai-stack/litellm/config.yaml:/app/config.yaml

    hostname: ${NAME:-litellm}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - ${PORT:-4000}:4000

    env_file:
      - ./litellm/.env

    stop_signal: SIGKILL

    devices:
      # - /dev/video0:/dev/video0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/uinput
      - /dev/uhid
      - /dev/snd
      - /dev/kmsg

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    command: [--config, /app/config.yaml, --detailed_debug]

    # shm_size: 1gb

    # healthcheck:  # Defines the health check configuration for the container
    #   test:
    #     - CMD-SHELL
    #     - python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')"  # Command to execute for health check
    #   interval: 30s  # Perform health check every 30 seconds
    #   timeout: 10s   # Health check command times out after 10 seconds
    #   retries: 3     # Retry up to 3 times if health check fails
    #   start_period: 40s  # Wait 40 seconds after container start before beginning health checks

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
