services:
  litellm:
    image: ${IMAGE:-docker.litellm.ai/berriai/litellm:main-stable}
    container_name: ${NAME:-litellm}
    restart: ${RESTART:-unless-stopped}

    build:
      context: ../../../DATA/ai-stack/litellm
      dockerfile: Dockerfile
      args:
        UID: ${PUID:-1000}
        GID: ${PGID:-1000}
        target: runtime

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true
      
      - DATABASE_URL=postgresql://llmproxy:dbpassword9090@db:5433/litellm
      - STORE_MODEL_IN_DB=True

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - litellm_data:/litellm
      - ../../../DATA/ai-stack/litellm/config.yaml:/app/config.yaml

    depends_on:
      - litellm-db  # Indicates that this service depends on the 'db' service, ensuring 'db' starts first

    hostname: ${NAME:-litellm}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - ${PORT:-4000}:4000

    env_file:
      - ./litellm/.env

    stop_signal: SIGKILL

    devices:
      # - /dev/video0:/dev/video0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/uinput
      - /dev/uhid
      - /dev/snd
      - /dev/kmsg

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    healthcheck:  # Defines the health check configuration for the container
      test:
        - CMD-SHELL
        - python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')"  # Command to execute for health check
      interval: 30s  # Perform health check every 30 seconds
      timeout: 10s   # Health check command times out after 10 seconds
      retries: 3     # Retry up to 3 times if health check fails
      start_period: 40s  # Wait 40 seconds after container start before beginning health checks

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  litellm-db:
    image: postgres:16
    container_name: litellm-db
    restart: always

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}

      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:universal-git|linuxserver/mods:universal-cron|lscr.io/linuxserver/mods:universal-unrar6
      # - DOCKER_HOST=
      - INSTALL_PACKAGES=libfuse2|git|gdb
      - RESTART_APP=true

      - POSTGRES_DB=litellm
      - POSTGRES_USER=llmproxy
      - POSTGRES_PASSWORD=dbpassword9090

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - litellm_db_data:/var/lib/postgresql/data # Persists Postgres data across container restarts

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - 5433:5432

    env_file:
      - ./litellm/.env

    stop_signal: SIGKILL

    devices:
      # - /dev/video0:/dev/video0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/uinputf
      - /dev/uhid
      - /dev/snd
      - /dev/kmsg

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d litellm -U llmproxy
      interval: 1s
      timeout: 5s
      retries: 10

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  litellm-prometheus:
    image: prom/prometheus
    container_name: litellm-prometheus
    restart: ${RESTART:-unless-stopped}

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - com.ouroboros.enable=true
      - autoheal=true
      - autoheal-app
      - autoheal-app=true
      - homarr-app=true
      - homarr

    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock

      - litellm_prometheus_data:/prometheus
      - ../../../DATA/ai-stack/litellm/prometheus.yml:/etc/prometheus/prometheus.yml

    hostname: ${NAME:-litellm-prometheus}

    # user: ${PUID:-1000}:${PGID:-1000}

    networks:
      host:
      ai-services:

    ports:
      - 9090:9090

    env_file:
      - ./litellm/.env

    devices:
      # - /dev/video0:/dev/video0
      - /dev/nvidia0:/dev/nvidia0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/uinput
      - /dev/uhid
      - /dev/snd
      - /dev/kmsg

    runtime: nvidia
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, graphics, utility]

    tty: true

    stdin_open: true

    # shm_size: 1gb

    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
