model_list:
  - model_name: ollama
    litellm_params:
      model: ollama/fake-model
      api_key: ollama-key
      api_base: http://0.0.0.0:11434

general_settings:
  master_key: sk-admin

litellm_settings:
  drop_params: True
  telemetry: False
