FROM lscr.io/linuxserver/webtop:ubuntu-kde

ENV DEBIAN_FRONTEND=noninteractive

# Combineer installatie en opschonen voor een kleinere image
RUN apt-get update && apt-get install -y \
    git cmake g++ pkg-config autoconf automake libtool libfftw3-dev libusb-1.0-0-dev libusb-dev libhidapi-dev libopengl-dev \
    qtbase5-dev qtchooser libqt5multimedia5-plugins qtmultimedia5-dev libqt5websockets5-dev \
    qttools5-dev qttools5-dev-tools libqt5opengl5-dev libqt5quick5 libqt5charts5-dev \
    qml-module-qtlocation qml-module-qtpositioning qml-module-qtquick-window2 \
    qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-layouts \
    libqt5serialport5-dev qtdeclarative5-dev qtpositioning5-dev qtlocation5-dev libqt5texttospeech5-dev \
    qtwebengine5-dev qtbase5-private-dev libqt5gamepad5-dev libqt5svg5-dev \
    libfaad-dev libflac-dev zlib1g-dev libboost-all-dev libasound2-dev pulseaudio libopencv-dev libxml2-dev bison flex \
    ffmpeg libavcodec-dev libavformat-dev libopus-dev doxygen graphviz \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Bouw RTL-SDR (gefixte paden)
WORKDIR /opt/build/librtlsdr/build
RUN git clone https://github.com/osmocom/rtl-sdr.git .. && \
    git checkout 420086af84d7eaaf98ff948cd11fea2cae71734a && \
    cmake -Wno-dev -DDETACH_KERNEL_DRIVER=ON -DCMAKE_INSTALL_PREFIX=/opt/install/librtlsdr .. && \
    make -j$(nproc) install

# Bouw SDRANGEL (alleen met RTLSDR geactiveerd, rest weggelaten voor build-succes)
WORKDIR /opt/build/sdrangel/build
RUN git clone https://github.com/f4exb/sdrangel.git .. && \
    cmake -Wno-dev -DDEBUG_OUTPUT=ON -DRX_SAMPLE_24BIT=ON \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DRTLSDR_DIR=/opt/install/librtlsdr \
    -DCMAKE_INSTALL_PREFIX=/opt/install/sdrangel .. && \
    make -j$(nproc) install

# Omgevingsvariabelen
ENV LD_LIBRARY_PATH="/opt/install/librtlsdr/lib:/opt/install/sdrangel/lib:${LD_LIBRARY_PATH}"
ENV PATH="/opt/install/sdrangel/bin:${PATH}"

WORKDIR /config
EXPOSE 3000 3001
