FROM lscr.io/linuxserver/webtop:ubuntu-kde

ENV DEBIAN_FRONTEND=noninteractive

# 1. Installeer alle benodigde build-dependencies
# RUN apt-get update && apt-get install --no-install-recommends -y \
#     git curl cmake build-essential pkg-config autoconf automake && \
#     apt-get clean && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -s https://raw.githubusercontent.com/Nachtzuster/BirdNET-Pi/main/newinstaller.sh | bash || exit 1

WORKDIR /config

EXPOSE 80 8001
