FROM lscr.io/linuxserver/webtop:ubuntu-xfce

# Stap 1: Systeem dependencies
RUN apt-get update && apt-get install -y \
    wget unzip lib32gcc-s1 libsdl2-2.0-0 default-jre \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /config

# downloaden en installeren van Project Zomboid via GOG installer
# RUN mkdir -p /config/Downloads && \
#     wget -c "https://archive.org/download/gog_project_zomboid_41_78_16_60901_linux/project_zomboid_42_8_1_82488.sh" -O /config/Downloads/pz_install.sh
# RUN chmod +x /config/Downloads/pz_install.sh

RUN mkdir -p /config/custom-cont-init.d && \
    echo '#!/bin/bash\n\
    if [ ! -f "/config/GOG\ Games/Project\ Zomboid/start.sh" ]; then\n\
        echo "--- Project Zomboid wordt geinstalleerd ---"\n\
        su abc -c "DISPLAY=:1 /config/Downloads/pz_install.sh &"\n\
    else\n\
        echo "--- Project Zomboid wordt gestart ---"\n\
        su abc -c "DISPLAY=:1 /config/GOG\ Games/Project\ Zomboid/start.sh &"\n\
    fi' > /config/custom-cont-init.d/install-zomboid.sh && \
    chmod +x /config/custom-cont-init.d/install-zomboid.sh


# Rechten goedzetten voor de standaard webtop-gebruiker (abc)
RUN chown -R abc:abc /config

EXPOSE 3000 3001 16261