FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim

# ARG HOST_GID=1000
# ARG HOST_UID=1000

# 1. Installeer alle systeem-dependencies in één laag en schoon op
RUN apt-get update && apt-get install -y --no-install-recommends \
    git wget build-essential python3.11 python3.11-venv python3.11-dev \
    python3-pip ffmpeg libglib2.0-0 libgl1 \
    && rm -rf /var/lib/apt/lists/*

# 2. Stel de werkmap in op /SwarmUI
WORKDIR /SwarmUI
# COPY . /SwarmUI
RUN git clone --recursive https://github.com/mcmonkeyprojects/SwarmUI.git /SwarmUI

# RUN chown -R $HOST_UID:$HOST_UID /SwarmUI

# 3. Expose the port for other containers (to use Swarm as an API if you want)
EXPOSE 7801 8188

# 4. Start het launch-script
# ENTRYPOINT ["bash", "/SwarmUI/launchtools/docker-standard-inner.sh"]
