FROM lscr.io/linuxserver/webtop:ubuntu-kde

ENV DEBIAN_FRONTEND=noninteractive

# 1. Installeer alle benodigde build-dependencies
RUN apt-get update && apt-get install -y \
    git cmake build-essential pkg-config autoconf automake libtool libfftw3-dev libusb-1.0-0-dev libusb-dev libhidapi-dev libopengl-dev \
    qtbase5-dev qtchooser libqt5multimedia5-plugins qtmultimedia5-dev libqt5websockets5-dev \
    qttools5-dev qttools5-dev-tools libqt5opengl5-dev libqt5quick5 libqt5charts5-dev \
    qml-module-qtlocation qml-module-qtpositioning qml-module-qtquick-window2 \
    qml-module-qtquick-dialogs qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-layouts \
    libqt5serialport5-dev qtdeclarative5-dev qtpositioning5-dev qtlocation5-dev libqt5texttospeech5-dev \
    qtwebengine5-dev qtbase5-private-dev libqt5gamepad5-dev libqt5svg5-dev \
    libfaad-dev libflac-dev zlib1g-dev libboost-all-dev libasound2-dev pulseaudio libopencv-dev libxml2-dev bison flex \
    ffmpeg libavcodec-dev libavformat-dev libopus-dev doxygen graphviz \
    libsqlite3-dev libiio-dev libad9361-dev libsoapysdr-dev libsndfile-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# # --- Non-Hardware Libraries Bouwen ---

# WORKDIR /opt/build

# # APT
# RUN git clone https://github.com/srcejon/aptdec.git /opt/build/aptdec && \
#         cd /opt/build/aptdec && \
#         git checkout libaptdec && \
#         git submodule update --init --recursive && \
#         mkdir -p /opt/build/aptdec/build && cd /opt/build/aptdec/build && \
#         cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/aptdec .. && \
#         make -j$(nproc) install

# WORKDIR /opt/build

# # CM265cc
# RUN git clone https://github.com/f4exb/cm256cc.git /opt/build/cm256cc && \
#         cd /opt/build/cm256cc && \
#         git reset --hard 6f4a51802f5f302577d6d270a9fc0cb7a1ee28ef && \
#         mkdir -p /opt/build/cm256cc/build && cd /opt/build/cm256cc/build && \
#         cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/cm256cc .. && \
#         make -j$(nproc) install

# # LibDAB
# RUN git clone https://github.com/srcejon/dab-cmdline.git /opt/build/dab-cmdline && \
#                 cd /opt/build/dab-cmdline/library && \
#                 git checkout msvc && \
#                 mkdir -p /opt/build/dab-cmdline/build && cd /opt/build/cmdab-cmdline256cc/build && \
#                 cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/libdab .. && \
#                 make -j$(nproc) install

# --- Hardware Libraries Bouwen ---

WORKDIR /opt/build

# RTL-SDR
RUN git clone https://github.com/osmocom/rtl-sdr.git /opt/build/rtlsdr && \
    mkdir -p /opt/build/rtlsdr/build && cd /opt/build/rtlsdr/build && \
    cmake -DDETACH_KERNEL_DRIVER=ON -DCMAKE_INSTALL_PREFIX=/opt/install/librtlsdr .. && \
    make -j$(nproc) install

# --- SDRANGEL MAIN BUILD ---

WORKDIR /opt/build

RUN git clone https://github.com/f4exb/sdrangel.git /opt/build/sdrangel && \
    mkdir -p /opt/build/sdrangel/build && cd /opt/build/sdrangel/build && \
    cmake -Wno-dev -DDEBUG_OUTPUT=ON -DRX_SAMPLE_24BIT=ON \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DMIRISDR_DIR=/opt/install/libmirisdr \
    -DAIRSPY_DIR=/opt/install/libairspy \
    -DAIRSPYHF_DIR=/opt/install/libairspyhf \
    -DBLADERF_DIR=/opt/install/libbladeRF \
    -DHACKRF_DIR=/opt/install/libhackrf \
    -DRTLSDR_DIR=/opt/install/librtlsdr \
    -DLIMESUITE_DIR=/opt/install/LimeSuite \
    -DIIO_DIR=/opt/install/libiio \
    -DPERSEUS_DIR=/opt/install/libperseus \
    -DXTRX_DIR=/opt/install/xtrx-images \
    -DSOAPYSDR_DIR=/opt/install/SoapySDR \
    -DUHD_DIR=/opt/install/uhd \
    -DAPT_DIR=/opt/install/aptdec \
    -DCM256CC_DIR=/opt/install/cm256cc \
    -DDSDCC_DIR=/opt/install/dsdcc \
    -DSERIALDV_DIR=/opt/install/serialdv \
    -DMBE_DIR=/opt/install/mbelib \
    -DCODEC2_DIR=/opt/install/codec2 \
    -DSGP4_DIR=/opt/install/sgp4 \
    -DLIBSIGMF_DIR=/opt/install/libsigmf \
    -DDAB_DIR=/opt/install/libdab \
    -DGGMORSE_DIR=/opt/install/ggmorse \
    -DINMARSATC_DIR=/opt/install/inmarsatc \
    -DCMAKE_INSTALL_PREFIX=/opt/install/sdrangel .. && \
    make -j$(nproc) install

# Omgevingsvariabelen
ENV LD_LIBRARY_PATH="/opt/install/librtlsdr/lib:/opt/install/libairspy/lib:/opt/install/libairspyhf/lib:/opt/install/libhackrf/lib:/opt/install/libbladeRF/lib:/opt/install/LimeSuite/lib:/opt/install/libmirisdr/lib:/opt/install/mbelib/lib:/opt/install/serialdv/lib:/opt/install/dsdcc/lib:/opt/install/sdrangel/lib:${LD_LIBRARY_PATH}"
ENV PATH="/opt/install/sdrangel/bin:${PATH}"

WORKDIR /config
EXPOSE 3000 3001
